@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
<style>
.dash-hero{position:relative;overflow:hidden;margin-bottom:22px;padding:22px 24px;border:1px solid #e1e8f2;border-radius:16px;background:linear-gradient(120deg,#fff,#f7f9ff 62%,#eef2ff);box-shadow:0 10px 30px rgba(30,42,70,.06)}.dash-hero::after{content:"";position:absolute;right:-50px;top:-80px;width:210px;height:210px;border-radius:50%;background:radial-gradient(circle,rgba(83,109,254,.16),transparent 67%)}.dash-hero h2{margin:0 0 5px;color:#15213a;font-size:1.7rem;font-weight:780;letter-spacing:-.03em}.dash-hero p{margin:0;color:#758298;font-size:.86rem}.hero-kicker{display:flex;align-items:center;gap:7px;margin-bottom:8px;color:#5a6ee8;font-size:.64rem;font-weight:750;letter-spacing:.1em;text-transform:uppercase}
.metric-link{color:inherit;text-decoration:none}.metric{--tone:#536dfe;--soft:#eef1ff;position:relative;height:100%;overflow:hidden;padding:18px;border:1px solid #e6ebf3;border-radius:15px;background:#fff;box-shadow:0 8px 24px rgba(25,39,70,.06);transition:.2s}.metric:hover{transform:translateY(-3px);box-shadow:0 14px 30px rgba(25,39,70,.1)}.metric::before{content:"";position:absolute;left:0;top:18px;bottom:18px;width:3px;border-radius:0 5px 5px 0;background:var(--tone)}.metric-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;color:var(--tone);background:var(--soft)}.metric-label{margin:12px 0 3px;color:#7b8799;font-size:.73rem;font-weight:650}.metric-value{color:#172033;font-size:1.5rem;line-height:1;font-weight:780;letter-spacing:-.03em}
.dash-panel{overflow:hidden;border:1px solid #e5eaf2;border-radius:15px;background:#fff;box-shadow:0 8px 25px rgba(25,39,70,.055)}.dash-panel+.dash-panel{margin-top:22px}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:15px 18px;border-bottom:1px solid #edf0f5;background:linear-gradient(#fff,#fbfcfe)}.panel-title{display:flex;align-items:center;gap:9px;margin:0;color:#25324a;font-size:.94rem;font-weight:750}.panel-title i{width:31px;height:31px;display:grid;place-items:center;border-radius:9px;color:#536dfe;background:#eef1ff}.panel-meta{color:#97a1b1;font-size:.67rem}.panel-body{padding:7px 18px 13px}.dash-table{margin:0}.dash-table th{padding:12px 10px;color:#8792a4;border-bottom-color:#e8edf4;font-size:.67rem;font-weight:750;letter-spacing:.05em;text-transform:uppercase}.dash-table td{padding:13px 10px;color:#465267;border-bottom-color:#edf1f5;font-size:.77rem}.dash-table tr:last-child td{border-bottom:0}.dash-table .badge{padding:5px 8px;border-radius:7px;font-size:.64rem}
.empty-state{padding:25px 12px!important;text-align:center!important;color:#98a2b2!important}.empty-state i{display:block;margin-bottom:6px;color:#c0c8d5;font-size:1.35rem}.empty-state strong{display:block;color:#667287;font-size:.78rem}.empty-state small{font-size:.68rem}.cat-list{padding:7px 16px 13px}.cat-row{display:flex;align-items:center;gap:11px;padding:12px 2px;border-bottom:1px solid #edf1f5}.cat-row:last-child{border-bottom:0}.cat-dot{width:9px;height:9px;border-radius:50%;background:var(--dot);box-shadow:0 0 0 4px color-mix(in srgb,var(--dot),transparent 85%)}.cat-name{flex:1;color:#49566b;font-size:.78rem}.cat-count{min-width:29px;padding:4px 8px;text-align:center;border-radius:8px;color:#4d5ed2;background:#eef1ff;font-size:.68rem;font-weight:750}.inventory-alert{margin-bottom:22px;padding:13px 15px;border:1px solid #f5d889;border-radius:13px;background:#fffaf0;color:#6b5520;font-size:.78rem}
.value-card{padding:16px;border:1px solid #e5eaf2;border-radius:14px;background:#fff}.value-card small{color:#7f8a9c;font-size:.68rem}.value-card strong{display:block;margin-top:4px;color:#24324a;font-size:1.15rem}.trend-chart{height:180px;display:flex;align-items:flex-end;gap:10px;padding-top:18px}.trend-day{flex:1;height:100%;display:flex;align-items:flex-end;justify-content:center;gap:4px;position:relative;padding-bottom:24px}.trend-day i{width:18%;min-width:7px;border-radius:5px 5px 2px 2px}.trend-day .stock-in{height:var(--in);background:#42c7a5}.trend-day .stock-out{height:var(--out);background:#6574ee}.trend-day b{position:absolute;bottom:0;color:#8b96a8;font-size:.62rem}.chart-key{display:flex;gap:14px;color:#7d899b;font-size:.66rem}.chart-key span::before{content:"";display:inline-block;width:8px;height:8px;margin-right:5px;border-radius:3px;background:var(--c)}
</style>

<section class="dash-hero"><div class="hero-kicker"><i class="bi bi-activity"></i>Live inventory overview</div><h2>Dashboard</h2><p>Monitor stock levels, product activity, and inventory health at a glance.</p></section>

@if($lowStock || $outOfStock || $expiringSoon || $expiredProducts)
<div class="inventory-alert d-flex flex-wrap justify-content-between align-items-center gap-2"><div><i class="bi bi-exclamation-triangle-fill me-2 text-warning"></i><strong>Inventory alerts require attention.</strong> Low/out of stock: {{ $lowStock + $outOfStock }}; expiring/expired: {{ $expiringSoon + $expiredProducts }}.</div><div><a href="{{ route('batch-inventory.index') }}" class="btn btn-sm btn-dark">View Batches</a> <a href="{{ route('expiration.index') }}" class="btn btn-sm btn-danger">View Expiration</a></div></div>
@endif

@php
$metrics=[
['Total Products',$totalProducts,'bi-box-seam','#536dfe','#eef1ff',route('products.index')],
['Total Stock',number_format($totalStock,2),'bi-boxes','#0ea5a8','#e9fbf8',null],
['Low Stock',$lowStock,'bi-graph-down-arrow','#f0a500','#fff8df',null],
['Out of Stock',$outOfStock,'bi-x-circle','#ef4444','#fff0f1',null],
['Expiring Soon',$expiringSoon,'bi-hourglass-split','#2979ff','#edf5ff',null],
['Expired',$expiredProducts,'bi-calendar-x','#dc3545','#fff0f2',null]
];
@endphp
<div class="row g-3 mb-4">@foreach($metrics as $m)<div class="col-6 col-md-4 col-xl-2">@if($m[5])<a class="metric-link" href="{{ $m[5] }}">@endif<div class="metric" style="--tone:{{ $m[3] }};--soft:{{ $m[4] }}"><div class="d-flex justify-content-between"><span class="metric-icon"><i class="bi {{ $m[2] }}"></i></span><i class="bi bi-arrow-up-right text-secondary opacity-25"></i></div><div class="metric-label">{{ $m[0] }}</div><div class="metric-value">{{ $m[1] }}</div></div>@if($m[5])</a>@endif</div>@endforeach</div>

@php $maxFlow=max(1,$trend->max(fn($d)=>max($d['in'],$d['out']))); @endphp
<div class="row g-4 mb-4"><div class="col-xl-7"><section class="dash-panel h-100"><div class="panel-head"><h3 class="panel-title"><i class="bi bi-bar-chart"></i>7-Day Stock Movement</h3><div class="chart-key"><span style="--c:#42c7a5">Stock In</span><span style="--c:#6574ee">Stock Out</span></div></div><div class="panel-body"><div class="trend-chart">@foreach($trend as $day)<div class="trend-day"><i class="stock-in" style="--in:{{ max(3,($day['in']/$maxFlow)*100) }}%" title="Stock In: {{ $day['in'] }}"></i><i class="stock-out" style="--out:{{ max(3,($day['out']/$maxFlow)*100) }}%" title="Stock Out: {{ $day['out'] }}"></i><b>{{ $day['label'] }}</b></div>@endforeach</div></div></section></div><div class="col-xl-5"><div class="row g-3"><div class="col-6"><div class="value-card"><small>Inventory Cost</small><strong>&#8369;{{ number_format((float)$inventoryCostValue,2) }}</strong></div></div><div class="col-6"><div class="value-card"><small>Retail Value</small><strong>&#8369;{{ number_format((float)$inventoryRetailValue,2) }}</strong></div></div><div class="col-6"><div class="value-card"><small>Potential Profit</small><strong class="text-success">&#8369;{{ number_format((float)$estimatedProfit,2) }}</strong></div></div></div></div></div>

<div class="row g-4 align-items-start"><div class="col-xl-8">
<section class="dash-panel"><div class="panel-head"><h3 class="panel-title"><i class="bi bi-clock-history"></i>Recent Products</h3><span class="panel-meta">Latest inventory entries</span></div><div class="panel-body table-responsive"><table class="table dash-table align-middle"><thead><tr><th>Product</th><th>Category</th><th>Stock</th><th>Price</th></tr></thead><tbody>
@forelse($recentProducts as $product)<tr><td><strong>{{ $product->product_name }}</strong><br><small class="text-muted">{{ $product->product_code }}</small></td><td>{{ $product->category_label }}</td><td>@if($product->quantity<=0)<span class="badge bg-danger">Out of Stock</span>@elseif($product->quantity<=$product->minimum_stock)<span class="badge bg-warning text-dark">{{ $product->quantity }}</span>@else<span class="badge bg-success">{{ $product->quantity }}</span>@endif</td><td>&#8369;{{ number_format($product->selling_price,2) }}</td></tr>@empty<tr><td colspan="4" class="empty-state"><i class="bi bi-box-seam"></i><strong>No products available</strong><small>Add your first product to see it here.</small></td></tr>@endforelse
</tbody></table></div></section>

<section class="dash-panel"><div class="panel-head"><h3 class="panel-title"><i class="bi bi-exclamation-triangle"></i>Low Stock Products</h3><span class="panel-meta">Items requiring attention</span></div><div class="panel-body table-responsive"><table class="table dash-table align-middle"><thead><tr><th>Product</th><th>Category</th><th>Current Stock</th><th>Minimum</th></tr></thead><tbody>
@forelse($lowStockProducts as $product)<tr><td><strong>{{ $product->product_name }}</strong></td><td>{{ $product->category_label }}</td><td><span class="badge bg-danger">{{ $product->quantity }}</span></td><td>{{ $product->minimum_stock }}</td></tr>@empty<tr><td colspan="4" class="empty-state"><i class="bi bi-shield-check"></i><strong>Stock levels look healthy</strong><small>No low-stock products right now.</small></td></tr>@endforelse
</tbody></table></div></section></div>

<div class="col-xl-4"><section class="dash-panel"><div class="panel-head"><h3 class="panel-title"><i class="bi bi-pie-chart"></i>Products by Category</h3><span class="panel-meta">{{ $categories->count() }} categories</span></div><div class="cat-list">@forelse($categories as $category)<div class="cat-row"><span class="cat-dot" style="--dot:{{ ['#536dfe','#0ea5a8','#f0a500','#ef5d76','#8b5cf6','#2979ff'][$loop->index%6] }}"></span><span class="cat-name">{{ $category->name }}</span><span class="cat-count">{{ $category->products_count }}</span></div>@empty<div class="empty-state"><i class="bi bi-tags"></i><strong>No categories yet</strong><small>Create categories to organize products.</small></div>@endforelse</div></section></div></div>
@endsection
