<?php
namespace App\Http\Controllers;
use App\Models\PurchaseOrder; use App\Models\Product; use App\Models\ProductBatch; use App\Models\PurchaseOrderReceipt; use App\Models\StockIn; use App\Models\Supplier; use App\Services\ActivityLogger; use App\Services\InventoryMovementService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class PurchaseOrderController extends Controller {
 public function index(){ $orders=PurchaseOrder::with('supplier')->latest()->paginate(20); return view('purchase-orders.index',compact('orders')); }
 public function create(){ $suppliers=Supplier::where('status',true)->orderBy('supplier_name')->get(); $products=Product::where('status',true)->orderBy('product_name')->get(); return view('purchase-orders.create',compact('suppliers','products')); }
 public function store(Request $r){$v=$r->validate(['supplier_id'=>'required|exists:suppliers,id','order_date'=>'required|date','expected_date'=>'nullable|date|after_or_equal:order_date','notes'=>'nullable|string','product_id'=>'required|array|min:1','product_id.*'=>'required|exists:products,id','quantity.*'=>'required|numeric|min:.01','unit_cost.*'=>'required|numeric|min:0','expiration_date.*'=>'nullable|date']);$po=DB::transaction(function()use($v){$po=PurchaseOrder::create(['po_number'=>'PO-'.now()->format('YmdHis').'-'.random_int(100,999),'supplier_id'=>$v['supplier_id'],'created_by'=>auth()->id(),'status'=>'draft','approval_status'=>'pending','order_date'=>$v['order_date'],'expected_date'=>$v['expected_date']??null,'notes'=>$v['notes']??null,'total_amount'=>0]);$total=0;foreach($v['product_id'] as $i=>$id){$qty=$v['quantity'][$i];$cost=$v['unit_cost'][$i];$po->items()->create(['product_id'=>$id,'quantity'=>$qty,'unit_cost'=>$cost,'expiration_date'=>$v['expiration_date'][$i]??null]);$total+=$qty*$cost;}$po->update(['total_amount'=>$total]);return $po;});ActivityLogger::log('Created','Purchase Orders','Created '.$po->po_number.' awaiting approval.');return redirect()->route('purchase-orders.show',$po)->with('success','Purchase order created and submitted for approval.');}
 public function show(PurchaseOrder $purchaseOrder){$purchaseOrder->load(['supplier','items.product','creator','approver','receipts.receiver']);return view('purchase-orders.show',compact('purchaseOrder'));}
 public function approve(PurchaseOrder $purchaseOrder){abort_if($purchaseOrder->status==='cancelled',422,'Cancelled orders cannot be approved.');abort_if($purchaseOrder->approval_status==='approved',422,'Purchase order is already approved.');$purchaseOrder->update(['approval_status'=>'approved','approved_by'=>auth()->id(),'approved_at'=>now(),'status'=>'ordered']);ActivityLogger::log('Approved','Purchase Orders','Approved '.$purchaseOrder->po_number.'.');return back()->with('success','Purchase order approved.');}
 public function receive(Request $request, PurchaseOrder $purchaseOrder, InventoryMovementService $movements){$v=$request->validate(['remarks'=>'nullable|string|max:1000']);DB::transaction(function()use($purchaseOrder,$movements,$v){$order=PurchaseOrder::whereKey($purchaseOrder->id)->lockForUpdate()->firstOrFail();abort_if(in_array($order->status,['received','cancelled']),422,'Order cannot be received.');if($order->approval_status==='pending' && $order->status==='draft')throw ValidationException::withMessages(['purchase_order'=>'Purchase order must be approved before receiving.']);$order->load('items.product');$receiptNumber=$order->receipts()->count()+1;$receipt=PurchaseOrderReceipt::create(['purchase_order_id'=>$order->id,'received_by'=>auth()->id(),'reference_number'=>$order->po_number.'-R'.$receiptNumber,'received_date'=>today(),'remarks'=>$v['remarks']??null]);foreach($order->items as $item){$qty=(float)$item->quantity-(float)$item->received_quantity;if($qty<=0)continue;$batch='PO-'.$order->id.'-'.$item->id.'-R'.$receipt->id;$stock=StockIn::create(['product_id'=>$item->product_id,'supplier_id'=>$order->supplier_id,'quantity'=>$qty,'cost_price'=>$item->unit_cost,'batch_number'=>$batch,'expiration_date'=>$item->expiration_date,'reference_number'=>$receiptNumber===1?$order->po_number:$receipt->reference_number,'stock_in_date'=>today(),'remarks'=>$v['remarks']??'Received from purchase order.']);$productBatch=ProductBatch::create(['product_id'=>$item->product_id,'stock_in_id'=>$stock->id,'batch_number'=>$batch,'quantity'=>$qty,'expiration_date'=>$item->expiration_date,'received_date'=>today()]);$item->product->increment('quantity',$qty);$item->increment('received_quantity',$qty);$movements->record(['product_id'=>$item->product_id,'product_batch_id'=>$productBatch->id,'movement_type'=>'purchase_order_receive','quantity'=>$qty,'source_type'=>StockIn::class,'source_id'=>$stock->id,'movement_date'=>today(),'remarks'=>'Received from '.$order->po_number]);}$order->update(['status'=>$order->items()->whereColumn('received_quantity','<','quantity')->exists()?'partial':'received']);});ActivityLogger::log('Received','Purchase Orders','Received '.$purchaseOrder->po_number.'.');return back()->with('success','Purchase order receipt recorded.');}
 public function cancel(Request $request, PurchaseOrder $purchaseOrder){$v=$request->validate(['cancellation_reason'=>'required|string|min:5|max:1000']);abort_if($purchaseOrder->status==='received',422,'Received orders cannot be cancelled.');$purchaseOrder->update(['status'=>'cancelled','cancellation_reason'=>$v['cancellation_reason']]);ActivityLogger::log('Cancelled','Purchase Orders','Cancelled '.$purchaseOrder->po_number.': '.$v['cancellation_reason']);return back()->with('success','Purchase order cancelled.');}
}
